steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/receipt-storage-wallet-api:$COMMIT_SHA',
      '-t',
      'gcr.io/$PROJECT_ID/receipt-storage-wallet-api:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/receipt-storage-wallet-api:$COMMIT_SHA'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/receipt-storage-wallet-api:latest'
    ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'receipt-storage-wallet-api',
      '--image',
      'gcr.io/$PROJECT_ID/receipt-storage-wallet-api:$COMMIT_SHA',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated',
      '--port',
      '8081',
      '--memory',
      '2Gi',
      '--cpu',
      '2',
      '--max-instances',
      '10',
      '--set-env-vars',
      'GOOGLE_PROJECT_ID=$PROJECT_ID',
      '--set-env-vars',
      'GOOGLE_API_KEY=${_GOOGLE_API_KEY}',
      '--set-env-vars',
      'WALLET_ISSUER_ID=${_WALLET_ISSUER_ID}',
      '--set-env-vars',
      'WALLET_CLASS_ID=${_WALLET_CLASS_ID}'
    ]

images:
  - 'gcr.io/$PROJECT_ID/receipt-storage-wallet-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/receipt-storage-wallet-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

substitutions:
  _GOOGLE_API_KEY: 'your-google-api-key'
  _WALLET_ISSUER_ID: 'your-wallet-issuer-id'
  _WALLET_CLASS_ID: 'your-wallet-class-id'
